"use strict";
exports.__esModule = true;
var address_1 = require("./address");
var Bus_1 = require("./Bus");
var customer_1 = require("./customer");
var Trip_1 = require("./Trip");
var mytrip = new Trip_1.Trip("Trip Khmer");
var addressDeparture1 = new address_1.Address("Phnom Penh", "Cambodia");
var addressArrival1 = new address_1.Address("Kampot", "Cambodia");
var addressDeparture2 = new address_1.Address("Phnom Penh", "Cambodia");
var addressArrival2 = new address_1.Address("Phnom Penh", "Sieam Reap");
var customerA = new customer_1.Customer("Him", "Hey", false);
var customerB = new customer_1.Customer("Sovanda", "Chib", true);
var customerC = new customer_1.Customer("Ronan", "Ogor", true);
var bus1 = new Bus_1.Bus("KAKA Bus");
var bus2 = new Bus_1.Bus("LYHOR Express");
bus1.addAddress(addressDeparture1);
bus1.addAddress(addressArrival1);
bus1.addCustomer(customerB);
bus1.addCustomer(customerC);
bus2.addAddress(addressDeparture2);
bus2.addAddress(addressArrival2);
bus2.addCustomer(customerA);
bus2.addCustomer(customerB);
bus2.addCustomer(customerC);
mytrip.addBus(bus1);
mytrip.addBus(bus2);
mytrip.bus.forEach(function (item) {
    console.log(item.name);
});
